---
- hosts: all
  gather_facts: false
  connection: local
  
  vars:
    cli:
      username: lab
      password: lab123


  tasks:

     - name: pull device configurations y
       junos_command:
          provider: "{{cli}} "
          commands: show configuration | no-more

       register: junos_configs
       debug: junos_configs

     
